FROM php:5.6-fpm

ENV DEBIAN_FRONTEND=noninteractive \
    COMPOSER_HOME=/root/.composer

## Get packages for composer
RUN apt-get update -q -y \
 && apt-get install -q -y --force-yes --no-install-recommends \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libxpm-dev \
        libpng12-dev \
        libicu-dev \
        libxslt1-dev \
        libmcrypt-dev \
        ca-certificates \
        curl \
        acl \
        sudo \
        unzip \
        git \
        && rm -rf /var/lib/apt/lists/*

# Install and configure php plugin
RUN docker-php-source extract \
 && docker-php-ext-configure mysql --with-mysql=mysqlnd \
 && docker-php-ext-configure mysqli --with-mysqli=mysqlnd \
 && docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
 && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/ --with-xpm-dir=/usr/include/ --enable-gd-native-ttf --enable-gd-jis-conv \
 && docker-php-ext-install exif gd mbstring intl xsl zip mysqli pdo_mysql mysql mcrypt \
 && docker-php-ext-enable opcache

# Create Composer directory (cache and auth files) & Get Composer
RUN mkdir -p $COMPOSER_HOME \
 && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Enable mod_rewrite
RUN a2enmod rewrite

# Display version information
RUN php --version
RUN composer --version
